require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")

require 'json'
podfile_properties = JSON.parse(File.read(File.join(__dir__, 'Podfile.properties.json'))) rescue {}

platform :ios, podfile_properties['ios.deploymentTarget'] || '15.1'
prepare_react_native_project!

target 'zellix' do
  use_expo_modules!
  config = use_native_modules!

  use_frameworks! :linkage => :static
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == nil || podfile_properties['expo.jsEngine'] == 'hermes',
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # Fix for all React Native Firebase modules
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['DEFINES_MODULE'] = 'YES'
        
        # Fix header search paths for RNFB
        if target.name.include?('RNFB')
          config.build_settings['HEADER_SEARCH_PATHS'] = [
            '$(inherited)',
            '"${PODS_ROOT}/Headers/Public/React-Core"',
            '"${PODS_ROOT}/Headers/Public/React"'
          ].join(' ')
        end
      end
    end

    react_native_post_install(installer, config[:reactNativePath])
  end
end